server:
  port: 8888

spring:
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/damonYuan/payment-config/
          searchPaths: ntt,fps
          default-label: main